# Site settings
title: Jonatan Männchen
email: jonatan@maennchen.ch
phone: +41 78 724 57 90
description: > # this means to ignore newlines until "baseurl:"
  Personal Homepage and Blog of Jonatan Männchen
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://maennchen.dev" # the base hostname & protocol for your site
twitter_username: maennchen_
github_username:  maennchen
asset_version: 1

# Build settings
markdown: kramdown
exclude:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile
  - .devcontainer.json
  - .github
  - .claude
  - .devenv*
  - devenv.*
  - .direnv
  - .envrc
  - .mcp.json
  - .ruby-lsp

# Sass
sass:
  style: :compressed